/*
Customer Shopping Behaviour Analysis
Author: Kosi Etimbuk-Udoekong

Objective:
Analyse customer shopping behaviour to understand purchasing patterns,
revenue drivers, subscription behaviour, product performance and
customer segments.

Database: PostgreSQL
*/


--Preview the dataset

SELECT *
FROM customer
LIMIT 20;


--Q1. What is the total revenue generated by male vs female customers?
SELECT gender,
     SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, discount_applied, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount) 
	  FROM customer
  );

--Q3. Which are the top 5 products with the highest review ratings?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS avg_review_rating
FROM customer 
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

--Q4. Compare the average purchase amounts between standard and express shipping
SELECT shipping_type, 
   ROUND(AVG(purchase_amount::numeric),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? 
--compare average spend and total revenue between subscribers and non-subscribers
SELECT ROUND(AVG(purchase_amount), 2) AS avg_spend,
  SUM(purchase_amount) AS total_revenue, subscription_status,
  COUNT(customer_id) AS total_customers
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal, 
--based on their total number of previous purchases, and show the count of each segment
SELECT 
      (CASE
	       WHEN previous_purchases <=1 THEN 'New'
		   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		   ELSE 'Loyal'
		   END) AS customer_segment,
		COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category?
WITH ranked_products AS (
     SELECT COUNT(*) AS purchase_count, category, item_purchased,
           ROW_NUMBER() OVER (
               PARTITION BY category
		       ORDER BY COUNT(*) DESC
	        ) AS product_rank
     FROM customer
     GROUP BY category, item_purchased
)
SELECT *
FROM ranked_products
WHERE product_rank <= 3;

--Q9. Are repeat customers (more than 5 previous purchases) also like to subscribe?
SELECT
    ROUND(
        COUNT(CASE WHEN subscription_status = 'Yes' THEN 1 END) * 100.0
        / COUNT(*),
        2
    ) AS subscribers,
	CASE
        WHEN previous_purchases > 5 THEN 'Repeat'
        ELSE 'Non-repeat'
END AS customer_type
FROM customer
GROUP BY customer_type;

--Q10. What is the revenue contribution of each age group?
SELECT
    MIN(age) AS youngest_age,
    MAX(age) AS oldest_age
FROM customer;

WITH age_groups AS (
	 SELECT 
	     purchase_amount,
           CASE
                WHEN age BETWEEN 18 AND 25 THEN '18-25'
                WHEN age BETWEEN 26 AND 35 THEN '26-35'
                WHEN age BETWEEN 36 AND 45 THEN '36-45'
                WHEN age BETWEEN 46 AND 55 THEN '46-55'
                WHEN age BETWEEN 56 AND 65 THEN '56-65'
                ELSE '66+'
            END AS age_group
FROM customer
)
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0
        / SUM(SUM(purchase_amount)) OVER (),
        2
    ) AS revenue_percentage
FROM age_groups
GROUP BY age_group
ORDER BY age_group;

SELECT age_group, 
   SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;